sampling:
  seed: 234
  shuffle: true

path:
  root: "./data/raw"

active_dataset: "cline9"

datasets:
  stl10:
    train_split: "train+unlabeled" # IMPORTANT: switch to "train+unlabeled" in real training 
    val_split: "test"
    train_size: 2000   # small size for pipeline debug, full size afterward
    val_size: 500  # small size for pipeline debug, full size afterward

  cifar10:
    train_split: "train"
    val_split: "train_subset" # CIFAR10 doesnt have val set, need to manual split a val set from train set
    val_ratio: 0.1  # control val set size
    train_size: 5000
    val_size: null

  # hugging face clane9/imagenet-100
  cline9:
    train_split: "train"
    val_split: "validation"
    train_size: 10000
    val_size: 2000

   