# SimCLR-style data augmentation configuration
augmentations:
  image_size: 224
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

  # Color & blur intensity parameters
  color_jitter:
    brightness: 0.8
    contrast: 0.8
    saturation: 0.8
    hue: 0.2
    p: 0.8

  gaussian_blur:
    kernel_scale: 0.1      # relative to image size
    p: 1.0

  random_grayscale:
    p: 0.2

  random_resized_crop:
    scale: [0.2, 1.0]
    ratio: [0.75, 1.3333]

  horizontal_flip:
    p: 0.5

  random_erase:
    use: true
    p: 0.2
    scale: [0.02, 0.2]
    ratio: [0.3, 3.3]
