sampling:
  seed: 234

dataset:
  name: "ilee0022/ImageNet100"
  output_subdir: "data/raw"
  splits:
    train: "train"
    val: "validation"
    test: "test"
  sizes:
    train: null
    val: null
    test: null

clean:
  name: "ilee0022/ImageNet100"
  cache_dir: "data/raw/ilee0022___image_net100/default/0.0.0/c55b2f2967c034db17be30f7d430e41c80fd4281"
  save_dir: "data/processed"
  
  
   