# DINOv2 Self-Supervised Visual Pretraining Stage
description: "1 - Self-supervised visual representation learning on ImageNet-100 using DINOv2 framework."

train:
  seed: 42
  epochs: 4
  batch_size: 32
  learning_rate: 0.00003
  weight_decay: 0.04
  momentum_teacher: 0.996
  warmup_epochs: 2
  save_dir: "runs/dinov2_exp2"
  accumulate_grad_batches: 2   # 可选梯度累积
  precision: "16-mixed"
  # resume_from_checkpoint: null
  gradient_clip_val: 0.5
  early_stop_patience: 2
  early_stop_min_delta: 0.0001

data:
  name: "ilee0022/ImageNet100"
  cache_dir: "data/processed"
  global_size: 224
  local_size: 96
  n_global: 2
  n_local: 2

model:
  # backbone: "vit_base_patch16_224"
  backbone: "vit_small_patch16_224"
  projection_dim: 256
  hidden_dim: 2048
  use_teacher: true
  temperature_student: 0.4
  temperature_teacher: 0.1
  temperature_teacher_warmup: 0.05
  center_momentum: 0.99  # essay 0.996