# Linear Probe Evaluation Stage
description: "2 - Evaluate DINOv2 encoder representations by training a linear classifier on ImageNet-100."

train:
  seed: 42
  epochs: 6
  batch_size: 64
  learning_rate: 0.0005
  weight_decay: 0.0001
  accumulate_grad_batches: 1
  precision: 32
  gradient_clip_val: 1.0
  early_stop_patience: 2
  early_stop_min_delta: 0.0001
  save_dir: "runs/linear_probe_exp1"
  log_every_n_steps: 10

data:
  name: "ilee0022/ImageNet100"
  cache_dir: "data/processed"
  global_size: 224
  num_classes: 100

model:
  backbone: "vit_small_patch16_224"
  num_classes: 100
  ckpt_path: "runs/dinov2_exp1/dinov2-00-0.000-v1.ckpt" 
  freeze_backbone: true